package countrydata

var countryCodeAlpha2MapByCountry = map[string]string{
	"Afghanistan":                       "AF",
	"Åland Islands":                     "AX",
	"Albania":                           "AL",
	"Algeria":                           "DZ",
	"American Samoa":                    "AS",
	"Andorra":                           "AD",
	"Angola":                            "AO",
	"Anguilla":                          "AI",
	"Antarctica":                        "AQ",
	"Antigua and Barbuda":               "AG",
	"Argentina":                         "AR",
	"Armenia":                           "AM",
	"Aruba":                             "AW",
	"Australia":                         "AU",
	"Austria":                           "AT",
	"Azerbaijan":                        "AZ",
	"Bahamas":                           "BS",
	"Bahrain":                           "BH",
	"Bangladesh":                        "BD",
	"Barbados":                          "BB",
	"Belarus":                           "BY",
	"Belgium":                           "BE",
	"Belize":                            "BZ",
	"Benin":                             "BJ",
	"Bermuda":                           "BM",
	"Bhutan":                            "BT",
	"Bonaire":                           "Sint Eustatius and Saba",
	"Bosnia and Herzegovina":            "BA",
	"Botswana":                          "BW",
	"Bouvet Island":                     "BV",
	"Brazil":                            "BR",
	"British Indian Ocean Territory":    "IO",
	"Brunei Darussalam":                 "BN",
	"Bulgaria":                          "BG",
	"Burkina Faso":                      "BF",
	"Burundi":                           "BI",
	"Cambodia":                          "KH",
	"Cameroon":                          "CM",
	"Canada":                            "CA",
	"Cabo Verde":                        "CV",
	"Cayman Islands":                    "KY",
	"Central African Republic":          "CF",
	"Chad":                              "TD",
	"Chile":                             "CL",
	"China":                             "CN",
	"Christmas Island":                  "CX",
	"Colombia":                          "CO",
	"Comoros":                           "KM",
	"Congo":                             "CG",
	"Cook Islands":                      "CK",
	"Costa Rica":                        "CR",
	"Côte d'Ivoire":                     "CI",
	"Croatia":                           "HR",
	"Cuba":                              "CU",
	"Curaçao":                           "CW",
	"Cyprus":                            "CY",
	"Czechia":                           "CZ",
	"Denmark":                           "DK",
	"Djibouti":                          "DJ",
	"Dominica":                          "DM",
	"Dominican Republic":                "DO",
	"Ecuador":                           "EC",
	"Egypt":                             "EG",
	"El Salvador":                       "SV",
	"Equatorial Guinea":                 "GQ",
	"Eritrea":                           "ER",
	"Estonia":                           "EE",
	"Ethiopia":                          "ET",
	"Faroe Islands":                     "FO",
	"Fiji":                              "FJ",
	"Finland":                           "FI",
	"France":                            "FR",
	"French Guiana":                     "GF",
	"French Polynesia":                  "PF",
	"French Southern Territories":       "TF",
	"Gabon":                             "GA",
	"Gambia":                            "GM",
	"Georgia":                           "GE",
	"Germany":                           "DE",
	"Ghana":                             "GH",
	"Gibraltar":                         "GI",
	"Greece":                            "GR",
	"Greenland":                         "GL",
	"Grenada":                           "GD",
	"Guadeloupe":                        "GP",
	"Guam":                              "GU",
	"Guatemala":                         "GT",
	"Guernsey":                          "GG",
	"Guinea":                            "GN",
	"Guinea-Bissau":                     "GW",
	"Guyana":                            "GY",
	"Haiti":                             "HT",
	"Heard Island and McDonald Islands": "HM",
	"Holy See":                          "VA",
	"Honduras":                          "HN",
	"Hong Kong":                         "HK",
	"Hungary":                           "HU",
	"Iceland":                           "IS",
	"India":                             "IN",
	"Indonesia":                         "ID",
	"Iraq":                              "IQ",
	"Ireland":                           "IE",
	"Isle of Man":                       "IM",
	"Israel":                            "IL",
	"Italy":                             "IT",
	"Jamaica":                           "JM",
	"Japan":                             "JP",
	"Jersey":                            "JE",
	"Jordan":                            "JO",
	"Kazakhstan":                        "KZ",
	"Kenya":                             "KE",
	"Kiribati":                          "KI",
	"Kuwait":                            "KW",
	"Kyrgyzstan":                        "KG",
	"Lao People's Democratic Republic":  "LA",
	"Latvia":                            "LV",
	"Lebanon":                           "LB",
	"Lesotho":                           "LS",
	"Liberia":                           "LR",
	"Libya":                             "LY",
	"Liechtenstein":                     "LI",
	"Lithuania":                         "LT",
	"Luxembourg":                        "LU",
	"Macao":                             "MO",
	"North Macedonia":                   "MK",
	"Madagascar":                        "MG",
	"Malawi":                            "MW",
	"Malaysia":                          "MY",
	"Maldives":                          "MV",
	"Mali":                              "ML",
	"Malta":                             "MT",
	"Marshall Islands":                  "MH",
	"Martinique":                        "MQ",
	"Mauritania":                        "MR",
	"Mauritius":                         "MU",
	"Mayotte":                           "YT",
	"Mexico":                            "MX",
	"Monaco":                            "MC",
	"Mongolia":                          "MN",
	"Montenegro":                        "ME",
	"Montserrat":                        "MS",
	"Morocco":                           "MA",
	"Mozambique":                        "MZ",
	"Myanmar":                           "MM",
	"Namibia":                           "NA",
	"Nauru":                             "NR",
	"Nepal":                             "NP",
	"Netherlands":                       "NL",
	"Netherlands Antilles":              "AN",
	"New Caledonia":                     "NC",
	"New Zealand":                       "NZ",
	"Nicaragua":                         "NI",
	"Niger":                             "NE",
	"Nigeria":                           "NG",
	"Niue":                              "NU",
	"Norfolk Island":                    "NF",
	"Northern Mariana Islands":          "MP",
	"Norway":                            "NO",
	"Oman":                              "OM",
	"Pakistan":                          "PK",
	"Palau":                             "PW",
	"Palestine":                         "State of",
	"Panama":                            "PA",
	"Papua New Guinea":                  "PG",
	"Paraguay":                          "PY",
	"Peru":                              "PE",
	"Philippines":                       "PH",
	"Pitcairn":                          "PN",
	"Poland":                            "PL",
	"Portugal":                          "PT",
	"Puerto Rico":                       "PR",
	"Qatar":                             "QA",
	"Réunion":                           "RE",
	"Romania":                           "RO",
	"Russian Federation":                "RU",
	"Rwanda":                            "RW",
	"Saint Barthélemy":                  "BL",
	"Saint Helena":                      "Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis":             "KN",
	"Saint Lucia":                       "LC",
	"Saint Pierre and Miquelon":         "PM",
	"Saint Vincent and the Grenadines":  "VC",
	"Samoa":                             "WS",
	"San Marino":                        "SM",
	"Sao Tome and Principe":             "ST",
	"Saudi Arabia":                      "SA",
	"Senegal":                           "SN",
	"Serbia":                            "RS",
	"Seychelles":                        "SC",
	"Sierra Leone":                      "SL",
	"Singapore":                         "SG",
	"Slovakia":                          "SK",
	"Slovenia":                          "SI",
	"Solomon Islands":                   "SB",
	"Somalia":                           "SO",
	"South Africa":                      "ZA",
	"South Georgia and the South Sandwich Islands": "GS",
	"South Sudan":              "SS",
	"Spain":                    "ES",
	"Sri Lanka":                "LK",
	"Sudan":                    "SD",
	"Suriname":                 "SR",
	"Svalbard and Jan Mayen":   "SJ",
	"Eswatini":                 "SZ",
	"Sweden":                   "SE",
	"Switzerland":              "CH",
	"Syrian Arab Republic":     "SY",
	"Taiwan":                   "Province of China",
	"Tajikistan":               "TJ",
	"Tanzania":                 "United Republic of",
	"Thailand":                 "TH",
	"Timor-Leste":              "TL",
	"Togo":                     "TG",
	"Tokelau":                  "TK",
	"Tonga":                    "TO",
	"Trinidad and Tobago":      "TT",
	"Tunisia":                  "TN",
	"Turkey":                   "TR",
	"Turkmenistan":             "TM",
	"Turks and Caicos Islands": "TC",
	"Tuvalu":                   "TV",
	"Uganda":                   "UG",
	"Ukraine":                  "UA",
	"United Arab Emirates":     "AE",
	"United Kingdom of Great Britain and Northern Ireland": "GB",
	"United States of America":                             "US",
	"United States Minor Outlying Islands":                 "UM",
	"Uruguay":                                              "UY",
	"Uzbekistan":                                           "UZ",
	"Vanuatu":                                              "VU",
	"Vietnam":                                              "VN",
	"Wallis and Futuna":                                    "WF",
	"Western Sahara":                                       "EH",
	"Yemen":                                                "YE",
	"Zambia":                                               "ZM",
	"Zimbabwe":                                             "ZW",
}

var countryMapByAlpha2CountryCode = make(map[string]string)
var countryCodeAlpha3MapAlpha2CountryCode = map[string]string{
	"AF": "AFG",
	"AX": "ALA",
	"AL": "ALB",
	"DZ": "DZA",
	"AS": "ASM",
	"AD": "AND",
	"AO": "AGO",
	"AI": "AIA",
	"AQ": "ATA",
	"AG": "ATG",
	"AR": "ARG",
	"AM": "ARM",
	"AW": "ABW",
	"AU": "AUS",
	"AT": "AUT",
	"AZ": "AZE",
	"BS": "BHS",
	"BH": "BHR",
	"BD": "BGD",
	"BB": "BRB",
	"BY": "BLR",
	"BE": "BEL",
	"BZ": "BLZ",
	"BJ": "BEN",
	"BM": "BMU",
	"BT": "BTN",
	"BO": "BOL",
	"BQ": "BES",
	"BA": "BIH",
	"BW": "BWA",
	"BV": "BVT",
	"BR": "BRA",
	"IO": "IOT",
	"BN": "BRN",
	"BG": "BGR",
	"BF": "BFA",
	"BI": "BDI",
	"CV": "CPV",
	"KH": "KHM",
	"CM": "CMR",
	"CA": "CAN",
	"KY": "CYM",
	"CF": "CAF",
	"TD": "TCD",
	"CL": "CHL",
	"CN": "CHN",
	"CX": "CXR",
	"CC": "CCK",
	"CO": "COL",
	"KM": "COM",
	"CG": "COG",
	"CD": "COD",
	"CK": "COK",
	"CR": "CRI",
	"CI": "CIV",
	"HR": "HRV",
	"CU": "CUB",
	"CW": "CUW",
	"CY": "CYP",
	"CZ": "CZE",
	"DK": "DNK",
	"DJ": "DJI",
	"DM": "DMA",
	"DO": "DOM",
	"EC": "ECU",
	"EG": "EGY",
	"SV": "SLV",
	"GQ": "GNQ",
	"ER": "ERI",
	"EE": "EST",
	"SZ": "SWZ",
	"ET": "ETH",
	"FK": "FLK",
	"FO": "FRO",
	"FJ": "FJI",
	"FI": "FIN",
	"FR": "FRA",
	"GF": "GUF",
	"PF": "PYF",
	"TF": "ATF",
	"GA": "GAB",
	"GM": "GMB",
	"GE": "GEO",
	"DE": "DEU",
	"GH": "GHA",
	"GI": "GIB",
	"GR": "GRC",
	"GL": "GRL",
	"GD": "GRD",
	"GP": "GLP",
	"GU": "GUM",
	"GT": "GTM",
	"GG": "GGY",
	"GN": "GIN",
	"GW": "GNB",
	"GY": "GUY",
	"HT": "HTI",
	"HM": "HMD",
	"VA": "VAT",
	"HN": "HND",
	"HK": "HKG",
	"HU": "HUN",
	"IS": "ISL",
	"IN": "IND",
	"ID": "IDN",
	"IR": "IRN",
	"IQ": "IRQ",
	"IE": "IRL",
	"IM": "IMN",
	"IL": "ISR",
	"IT": "ITA",
	"JM": "JAM",
	"JP": "JPN",
	"JE": "JEY",
	"JO": "JOR",
	"KZ": "KAZ",
	"KE": "KEN",
	"KI": "KIR",
	"KP": "PRK",
	"KR": "KOR",
	"KW": "KWT",
	"KG": "KGZ",
	"LA": "LAO",
	"LV": "LVA",
	"LB": "LBN",
	"LS": "LSO",
	"LR": "LBR",
	"LY": "LBY",
	"LI": "LIE",
	"LT": "LTU",
	"LU": "LUX",
	"MO": "MAC",
	"MG": "MDG",
	"MW": "MWI",
	"MY": "MYS",
	"MV": "MDV",
	"ML": "MLI",
	"MT": "MLT",
	"MH": "MHL",
	"MQ": "MTQ",
	"MR": "MRT",
	"MU": "MUS",
	"YT": "MYT",
	"MX": "MEX",
	"FM": "FSM",
	"MD": "MDA",
	"MC": "MCO",
	"MN": "MNG",
	"ME": "MNE",
	"MS": "MSR",
	"MA": "MAR",
	"MZ": "MOZ",
	"MM": "MMR",
	"NA": "NAM",
	"NR": "NRU",
	"NP": "NPL",
	"NL": "NLD",
	"NC": "NCL",
	"NZ": "NZL",
	"NI": "NIC",
	"NE": "NER",
	"NG": "NGA",
	"NU": "NIU",
	"NF": "NFK",
	"MK": "MKD",
	"MP": "MNP",
	"NO": "NOR",
	"OM": "OMN",
	"PK": "PAK",
	"PW": "PLW",
	"PS": "PSE",
	"PA": "PAN",
	"PG": "PNG",
	"PY": "PRY",
	"PE": "PER",
	"PH": "PHL",
	"PN": "PCN",
	"PL": "POL",
	"PT": "PRT",
	"PR": "PRI",
	"QA": "QAT",
	"RE": "REU",
	"RO": "ROU",
	"RU": "RUS",
	"RW": "RWA",
	"BL": "BLM",
	"SH": "SHN",
	"KN": "KNA",
	"LC": "LCA",
	"MF": "MAF",
	"PM": "SPM",
	"VC": "VCT",
	"WS": "WSM",
	"SM": "SMR",
	"ST": "STP",
	"SA": "SAU",
	"SN": "SEN",
	"RS": "SRB",
	"SC": "SYC",
	"SL": "SLE",
	"SG": "SGP",
	"SX": "SXM",
	"SK": "SVK",
	"SI": "SVN",
	"SB": "SLB",
	"SO": "SOM",
	"ZA": "ZAF",
	"GS": "SGS",
	"SS": "SSD",
	"ES": "ESP",
	"LK": "LKA",
	"SD": "SDN",
	"SR": "SUR",
	"SJ": "SJM",
	"SE": "SWE",
	"CH": "CHE",
	"SY": "SYR",
	"TW": "TWN",
	"TJ": "TJK",
	"TZ": "TZA",
	"TH": "THA",
	"TL": "TLS",
	"TG": "TGO",
	"TK": "TKL",
	"TO": "TON",
	"TT": "TTO",
	"TN": "TUN",
	"TR": "TUR",
	"TM": "TKM",
	"TC": "TCA",
	"TV": "TUV",
	"UG": "UGA",
	"UA": "UKR",
	"AE": "ARE",
	"GB": "GBR",
	"US": "USA",
	"UM": "UMI",
	"UY": "URY",
	"UZ": "UZB",
	"VU": "VUT",
	"VE": "VEN",
	"VN": "VNM",
	"VG": "VGB",
	"VI": "VIR",
	"WF": "WLF",
	"EH": "ESH",
	"YE": "YEM",
	"ZM": "ZMB",
	"ZW": "ZWE",
}
var countryMapByAlpha3CountryCode = make(map[string]string)
var countryMapByAlpha3NumericCode = make(map[string]string)
var countryCodeAlpha2MapAlpha3CountryCode = make(map[string]string)
var countryCodeAlpha3MapByNumeric = map[string]string{
	"004": "AFG",
	"248": "ALA",
	"008": "ALB",
	"012": "DZA",
	"016": "ASM",
	"020": "AND",
	"024": "AGO",
	"660": "AIA",
	"010": "ATA",
	"028": "ATG",
	"032": "ARG",
	"051": "ARM",
	"533": "ABW",
	"036": "AUS",
	"040": "AUT",
	"031": "AZE",
	"044": "BHS",
	"048": "BHR",
	"050": "BGD",
	"052": "BRB",
	"112": "BLR",
	"056": "BEL",
	"084": "BLZ",
	"204": "BEN",
	"060": "BMU",
	"064": "BTN",
	"068": "BOL",
	"535": "BES",
	"070": "BIH",
	"072": "BWA",
	"074": "BVT",
	"076": "BRA",
	"086": "IOT",
	"096": "BRN",
	"100": "BGR",
	"854": "BFA",
	"108": "BDI",
	"132": "CPV",
	"116": "KHM",
	"120": "CMR",
	"124": "CAN",
	"136": "CYM",
	"140": "CAF",
	"148": "TCD",
	"152": "CHL",
	"156": "CHN",
	"162": "CXR",
	"166": "CCK",
	"170": "COL",
	"174": "COM",
	"178": "COG",
	"180": "COD",
	"184": "COK",
	"188": "CRI",
	"384": "CIV",
	"191": "HRV",
	"192": "CUB",
	"531": "CUW",
	"196": "CYP",
	"203": "CZE",
	"208": "DNK",
	"262": "DJI",
	"212": "DMA",
	"214": "DOM",
	"218": "ECU",
	"818": "EGY",
	"222": "SLV",
	"226": "GNQ",
	"232": "ERI",
	"233": "EST",
	"748": "SWZ",
	"231": "ETH",
	"238": "FLK",
	"234": "FRO",
	"242": "FJI",
	"246": "FIN",
	"250": "FRA",
	"254": "GUF",
	"258": "PYF",
	"260": "ATF",
	"266": "GAB",
	"270": "GMB",
	"268": "GEO",
	"276": "DEU",
	"288": "GHA",
	"292": "GIB",
	"300": "GRC",
	"304": "GRL",
	"308": "GRD",
	"312": "GLP",
	"316": "GUM",
	"320": "GTM",
	"831": "GGY",
	"324": "GIN",
	"624": "GNB",
	"328": "GUY",
	"332": "HTI",
	"334": "HMD",
	"336": "VAT",
	"340": "HND",
	"344": "HKG",
	"348": "HUN",
	"352": "ISL",
	"356": "IND",
	"360": "IDN",
	"364": "IRN",
	"368": "IRQ",
	"372": "IRL",
	"833": "IMN",
	"376": "ISR",
	"380": "ITA",
	"388": "JAM",
	"392": "JPN",
	"832": "JEY",
	"400": "JOR",
	"398": "KAZ",
	"404": "KEN",
	"296": "KIR",
	"408": "PRK",
	"410": "KOR",
	"414": "KWT",
	"417": "KGZ",
	"418": "LAO",
	"428": "LVA",
	"422": "LBN",
	"426": "LSO",
	"430": "LBR",
	"434": "LBY",
	"438": "LIE",
	"440": "LTU",
	"442": "LUX",
	"446": "MAC",
	"450": "MDG",
	"454": "MWI",
	"458": "MYS",
	"462": "MDV",
	"466": "MLI",
	"470": "MLT",
	"584": "MHL",
	"474": "MTQ",
	"478": "MRT",
	"480": "MUS",
	"175": "MYT",
	"484": "MEX",
	"583": "FSM",
	"498": "MDA",
	"492": "MCO",
	"496": "MNG",
	"499": "MNE",
	"500": "MSR",
	"504": "MAR",
	"508": "MOZ",
	"104": "MMR",
	"516": "NAM",
	"520": "NRU",
	"524": "NPL",
	"528": "NLD",
	"540": "NCL",
	"554": "NZL",
	"558": "NIC",
	"562": "NER",
	"566": "NGA",
	"570": "NIU",
	"574": "NFK",
	"807": "MKD",
	"580": "MNP",
	"578": "NOR",
	"512": "OMN",
	"586": "PAK",
	"585": "PLW",
	"275": "PSE",
	"591": "PAN",
	"598": "PNG",
	"600": "PRY",
	"604": "PER",
	"608": "PHL",
	"612": "PCN",
	"616": "POL",
	"620": "PRT",
	"630": "PRI",
	"634": "QAT",
	"638": "REU",
	"642": "ROU",
	"643": "RUS",
	"646": "RWA",
	"652": "BLM",
	"654": "SHN",
	"659": "KNA",
	"662": "LCA",
	"663": "MAF",
	"666": "SPM",
	"670": "VCT",
	"882": "WSM",
	"674": "SMR",
	"678": "STP",
	"682": "SAU",
	"686": "SEN",
	"688": "SRB",
	"690": "SYC",
	"694": "SLE",
	"702": "SGP",
	"534": "SXM",
	"703": "SVK",
	"705": "SVN",
	"090": "SLB",
	"706": "SOM",
	"710": "ZAF",
	"239": "SGS",
	"728": "SSD",
	"724": "ESP",
	"144": "LKA",
	"729": "SDN",
	"740": "SUR",
	"744": "SJM",
	"752": "SWE",
	"756": "CHE",
	"760": "SYR",
	"158": "TWN",
	"762": "TJK",
	"834": "TZA",
	"764": "THA",
	"626": "TLS",
	"768": "TGO",
	"772": "TKL",
	"776": "TON",
	"780": "TTO",
	"788": "TUN",
	"792": "TUR",
	"795": "TKM",
	"796": "TCA",
	"798": "TUV",
	"800": "UGA",
	"804": "UKR",
	"784": "ARE",
	"826": "GBR",
	"840": "USA",
	"581": "UMI",
	"858": "URY",
	"860": "UZB",
	"548": "VUT",
	"862": "VEN",
	"704": "VNM",
	"092": "VGB",
	"850": "VIR",
	"876": "WLF",
	"732": "ESH",
	"887": "YEM",
	"894": "ZMB",
	"716": "ZWE",
}
var numericCodeMapByCountryCodeAlpha2 = make(map[string]string)
var numericCodeMapByAlpha3CountryCode = make(map[string]string)
var countryCodeAlpha2MapByNumericCode = map[string]string{
	"004": "AF",
	"008": "AL",
	"010": "AQ",
	"012": "DZ",
	"016": "AS",
	"020": "AD",
	"024": "AO",
	"028": "AG",
	"031": "AZ",
	"032": "AR",
	"036": "AU",
	"040": "AT",
	"044": "BS",
	"048": "BH",
	"050": "BD",
	"051": "AM",
	"052": "BB",
	"056": "BE",
	"060": "BM",
	"064": "BT",
	"068": "BO",
	"070": "BA",
	"072": "BW",
	"074": "BV",
	"076": "BR",
	"084": "BZ",
	"086": "IO",
	"090": "SB",
	"092": "VG",
	"096": "BN",
	"100": "BG",
	"104": "MM",
	"108": "BI",
	"112": "BY",
	"116": "KH",
	"120": "CM",
	"124": "CA",
	"132": "CV",
	"136": "KY",
	"140": "CF",
	"144": "LK",
	"148": "TD",
	"152": "CL",
	"156": "CN",
	"158": "TW",
	"162": "CX",
	"166": "CC",
	"170": "CO",
	"174": "KM",
	"175": "YT",
	"178": "CG",
	"180": "CD",
	"184": "CK",
	"188": "CR",
	"191": "HR",
	"192": "CU",
	"196": "CY",
	"203": "CZ",
	"204": "BJ",
	"208": "DK",
	"212": "DM",
	"214": "DO",
	"218": "EC",
	"222": "SV",
	"226": "GQ",
	"231": "ET",
	"232": "ER",
	"233": "EE",
	"234": "FO",
	"238": "FK",
	"239": "GS",
	"242": "FJ",
	"246": "FI",
	"248": "AX",
	"250": "FR",
	"254": "GF",
	"258": "PF",
	"260": "TF",
	"262": "DJ",
	"266": "GA",
	"268": "GE",
	"270": "GM",
	"275": "PS",
	"276": "DE",
	"288": "GH",
	"292": "GI",
	"296": "KI",
	"300": "GR",
	"304": "GL",
	"308": "GD",
	"312": "GP",
	"316": "GU",
	"320": "GT",
	"324": "GN",
	"328": "GY",
	"332": "HT",
	"334": "HM",
	"336": "VA",
	"340": "HN",
	"344": "HK",
	"348": "HU",
	"352": "IS",
	"356": "IN",
	"360": "ID",
	"364": "IR",
	"368": "IQ",
	"372": "IE",
	"376": "IL",
	"380": "IT",
	"384": "CI",
	"388": "JM",
	"392": "JP",
	"398": "KZ",
	"400": "JO",
	"404": "KE",
	"408": "KP",
	"410": "KR",
	"414": "KW",
	"417": "KG",
	"418": "LA",
	"422": "LB",
	"426": "LS",
	"428": "LV",
	"430": "LR",
	"434": "LY",
	"438": "LI",
	"440": "LT",
	"442": "LU",
	"446": "MO",
	"450": "MG",
	"454": "MW",
	"458": "MY",
	"462": "MV",
	"466": "ML",
	"470": "MT",
	"474": "MQ",
	"478": "MR",
	"480": "MU",
	"484": "MX",
	"492": "MC",
	"496": "MN",
	"498": "MD",
	"499": "ME",
	"500": "MS",
	"504": "MA",
	"508": "MZ",
	"512": "OM",
	"516": "NA",
	"520": "NR",
	"524": "NP",
	"528": "NL",
	"530": "AN",
	"531": "CW",
	"533": "AW",
	"534": "SX",
	"535": "BQ",
	"540": "NC",
	"548": "VU",
	"554": "NZ",
	"558": "NI",
	"562": "NE",
	"566": "NG",
	"570": "NU",
	"574": "NF",
	"578": "NO",
	"580": "MP",
	"581": "UM",
	"583": "FM",
	"584": "MH",
	"585": "PW",
	"586": "PK",
	"591": "PA",
	"598": "PG",
	"600": "PY",
	"604": "PE",
	"608": "PH",
	"612": "PN",
	"616": "PL",
	"620": "PT",
	"624": "GW",
	"626": "TL",
	"630": "PR",
	"634": "QA",
	"638": "RE",
	"642": "RO",
	"643": "RU",
	"646": "RW",
	"652": "BL",
	"654": "SH",
	"659": "KN",
	"660": "AI",
	"662": "LC",
	"663": "MF",
	"666": "PM",
	"670": "VC",
	"674": "SM",
	"678": "ST",
	"682": "SA",
	"686": "SN",
	"688": "RS",
	"690": "SC",
	"694": "SL",
	"702": "SG",
	"703": "SK",
	"704": "VN",
	"705": "SI",
	"706": "SO",
	"710": "ZA",
	"716": "ZW",
	"724": "ES",
	"728": "SS",
	"729": "SD",
	"732": "EH",
	"740": "SR",
	"744": "SJ",
	"748": "SZ",
	"752": "SE",
	"756": "CH",
	"760": "SY",
	"762": "TJ",
	"764": "TH",
	"768": "TG",
	"772": "TK",
	"776": "TO",
	"780": "TT",
	"784": "AE",
	"788": "TN",
	"792": "TR",
	"795": "TM",
	"796": "TC",
	"798": "TV",
	"800": "UG",
	"804": "UA",
	"807": "MK",
	"818": "EG",
	"826": "GB",
	"831": "GG",
	"832": "JE",
	"833": "IM",
	"834": "TZ",
	"840": "US",
	"850": "VI",
	"854": "BF",
	"858": "UY",
	"860": "UZ",
	"862": "VE",
	"876": "WF",
	"882": "WS",
	"887": "YE",
	"894": "ZM",
}
var numericCodeMapByCountry = map[string]string{
	"Afghanistan":                       "004",
	"Åland Islands":                     "248",
	"Albania":                           "008",
	"Algeria":                           "012",
	"American Samoa":                    "016",
	"Andorra":                           "020",
	"Angola":                            "024",
	"Anguilla":                          "660",
	"Antarctica":                        "010",
	"Antigua and Barbuda":               "028",
	"Argentina":                         "032",
	"Armenia":                           "051",
	"Aruba":                             "533",
	"Australia":                         "036",
	"Austria":                           "040",
	"Azerbaijan":                        "031",
	"Bahamas":                           "044",
	"Bahrain":                           "048",
	"Bangladesh":                        "050",
	"Barbados":                          "052",
	"Belarus":                           "112",
	"Belgium":                           "056",
	"Belize":                            "084",
	"Benin":                             "204",
	"Bermuda":                           "060",
	"Bhutan":                            "064",
	"Bonaire":                           "Sint Eustatius and Saba",
	"Bosnia and Herzegovina":            "070",
	"Botswana":                          "072",
	"Bouvet Island":                     "074",
	"Brazil":                            "076",
	"British Indian Ocean Territory":    "086",
	"Brunei Darussalam":                 "096",
	"Bulgaria":                          "100",
	"Burkina Faso":                      "854",
	"Burundi":                           "108",
	"Cabo Verde":                        "132",
	"Cambodia":                          "116",
	"Cameroon":                          "120",
	"Canada":                            "124",
	"Cayman Islands":                    "136",
	"Central African Republic":          "140",
	"Chad":                              "148",
	"Chile":                             "152",
	"China":                             "156",
	"Christmas Island":                  "162",
	"Colombia":                          "170",
	"Comoros":                           "174",
	"Congo":                             "178",
	"Cook Islands":                      "184",
	"Costa Rica":                        "188",
	"Côte d'Ivoire":                     "384",
	"Croatia":                           "191",
	"Cuba":                              "192",
	"Curaçao":                           "531",
	"Cyprus":                            "196",
	"Czechia":                           "203",
	"Denmark":                           "208",
	"Djibouti":                          "262",
	"Dominica":                          "212",
	"Dominican Republic":                "214",
	"Ecuador":                           "218",
	"Egypt":                             "818",
	"El Salvador":                       "222",
	"Equatorial Guinea":                 "226",
	"Eritrea":                           "232",
	"Estonia":                           "233",
	"Eswatini":                          "748",
	"Ethiopia":                          "231",
	"Faroe Islands":                     "234",
	"Fiji":                              "242",
	"Finland":                           "246",
	"France":                            "250",
	"French Guiana":                     "254",
	"French Polynesia":                  "258",
	"French Southern Territories":       "260",
	"Gabon":                             "266",
	"Gambia":                            "270",
	"Georgia":                           "268",
	"Germany":                           "276",
	"Ghana":                             "288",
	"Gibraltar":                         "292",
	"Greece":                            "300",
	"Greenland":                         "304",
	"Grenada":                           "308",
	"Guadeloupe":                        "312",
	"Guam":                              "316",
	"Guatemala":                         "320",
	"Guernsey":                          "831",
	"Guinea":                            "324",
	"Guinea-Bissau":                     "624",
	"Guyana":                            "328",
	"Haiti":                             "332",
	"Heard Island and McDonald Islands": "334",
	"Holy See":                          "336",
	"Honduras":                          "340",
	"Hong Kong":                         "344",
	"Hungary":                           "348",
	"Iceland":                           "352",
	"India":                             "356",
	"Indonesia":                         "360",
	"Iraq":                              "368",
	"Ireland":                           "372",
	"Isle of Man":                       "833",
	"Israel":                            "376",
	"Italy":                             "380",
	"Jamaica":                           "388",
	"Japan":                             "392",
	"Jersey":                            "832",
	"Jordan":                            "400",
	"Kazakhstan":                        "398",
	"Kenya":                             "404",
	"Kiribati":                          "296",
	"Korea":                             "Republic of",
	"Kuwait":                            "414",
	"Kyrgyzstan":                        "417",
	"Lao People's Democratic Republic":  "418",
	"Latvia":                            "428",
	"Lebanon":                           "422",
	"Lesotho":                           "426",
	"Liberia":                           "430",
	"Libya":                             "434",
	"Liechtenstein":                     "438",
	"Lithuania":                         "440",
	"Luxembourg":                        "442",
	"Macao":                             "446",
	"Madagascar":                        "450",
	"Malawi":                            "454",
	"Malaysia":                          "458",
	"Maldives":                          "462",
	"Mali":                              "466",
	"Malta":                             "470",
	"Marshall Islands":                  "584",
	"Martinique":                        "474",
	"Mauritania":                        "478",
	"Mauritius":                         "480",
	"Mayotte":                           "175",
	"Mexico":                            "484",
	"Moldova":                           "Republic of",
	"Monaco":                            "492",
	"Mongolia":                          "496",
	"Montenegro":                        "499",
	"Montserrat":                        "500",
	"Morocco":                           "504",
	"Mozambique":                        "508",
	"Myanmar":                           "104",
	"Namibia":                           "516",
	"Nauru":                             "520",
	"Nepal":                             "524",
	"Netherlands":                       "528",
	"New Caledonia":                     "540",
	"New Zealand":                       "554",
	"Nicaragua":                         "558",
	"Niger":                             "562",
	"Nigeria":                           "566",
	"Niue":                              "570",
	"Norfolk Island":                    "574",
	"North Macedonia":                   "807",
	"Northern Mariana Islands":          "580",
	"Norway":                            "578",
	"Oman":                              "512",
	"Pakistan":                          "586",
	"Palau":                             "585",
	"Palestine":                         "State of",
	"Panama":                            "591",
	"Papua New Guinea":                  "598",
	"Paraguay":                          "600",
	"Peru":                              "604",
	"Philippines":                       "608",
	"Pitcairn":                          "612",
	"Poland":                            "616",
	"Portugal":                          "620",
	"Puerto Rico":                       "630",
	"Qatar":                             "634",
	"Réunion":                           "638",
	"Romania":                           "642",
	"Russian Federation":                "643",
	"Rwanda":                            "646",
	"Saint Barthélemy":                  "652",
	"Saint Helena":                      "Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis":             "659",
	"Saint Lucia":                       "662",
	"Saint Pierre and Miquelon":         "666",
	"Saint Vincent and the Grenadines":  "670",
	"Samoa":                             "882",
	"San Marino":                        "674",
	"Sao Tome and Principe":             "678",
	"Saudi Arabia":                      "682",
	"Senegal":                           "686",
	"Serbia":                            "688",
	"Seychelles":                        "690",
	"Sierra Leone":                      "694",
	"Singapore":                         "702",
	"Slovakia":                          "703",
	"Slovenia":                          "705",
	"Solomon Islands":                   "090",
	"Somalia":                           "706",
	"South Africa":                      "710",
	"South Georgia and the South Sandwich Islands": "239",
	"South Sudan":              "728",
	"Spain":                    "724",
	"Sri Lanka":                "144",
	"Sudan":                    "729",
	"Suriname":                 "740",
	"Svalbard and Jan Mayen":   "744",
	"Sweden":                   "752",
	"Switzerland":              "756",
	"Syrian Arab Republic":     "760",
	"Taiwan":                   "Province of China",
	"Tajikistan":               "762",
	"Tanzania":                 "United Republic of",
	"Thailand":                 "764",
	"Timor-Leste":              "626",
	"Togo":                     "768",
	"Tokelau":                  "772",
	"Tonga":                    "776",
	"Trinidad and Tobago":      "780",
	"Tunisia":                  "788",
	"Turkey":                   "792",
	"Turkmenistan":             "795",
	"Turks and Caicos Islands": "796",
	"Tuvalu":                   "798",
	"Uganda":                   "800",
	"Ukraine":                  "804",
	"United Arab Emirates":     "784",
	"United Kingdom of Great Britain and Northern Ireland": "826",
	"United States of America":                             "840",
	"United States Minor Outlying Islands":                 "581",
	"Uruguay":                                              "858",
	"Uzbekistan":                                           "860",
	"Vanuatu":                                              "548",
	"Vietnam":                                              "704",
	"Wallis and Futuna":                                    "876",
	"Western Sahara":                                       "732",
	"Yemen":                                                "887",
	"Zambia":                                               "894",
	"Zimbabwe":                                             "716",
}
var countryMapByNumeric = make(map[string]string)
var phoneCodeMapByCountry = map[string]string{
	"Afghanistan":                       "93",
	"Åland Islands":                     "358",
	"Albania":                           "355",
	"Algeria":                           "213",
	"American Samoa":                    "1-684",
	"Andorra":                           "376",
	"Angola":                            "244",
	"Anguilla":                          "1-264",
	"Antarctica":                        "672",
	"Antigua and Barbuda":               "1-268",
	"Argentina":                         "54",
	"Armenia":                           "374",
	"Aruba":                             "297",
	"Australia":                         "61",
	"Austria":                           "43",
	"Azerbaijan":                        "994",
	"Bahamas":                           "1-242",
	"Bahrain":                           "973",
	"Bangladesh":                        "880",
	"Barbados":                          "1-246",
	"Belarus":                           "375",
	"Belgium":                           "32",
	"Belize":                            "501",
	"Benin":                             "229",
	"Bermuda":                           "1-441",
	"Bhutan":                            "975",
	"Bonaire":                           "Sint Eustatius and Saba",
	"Bosnia and Herzegovina":            "387",
	"Botswana":                          "267",
	"Bouvet Island":                     "55",
	"Brazil":                            "55",
	"British Indian Ocean Territory":    "246",
	"Brunei Darussalam":                 "673",
	"Bulgaria":                          "359",
	"Burkina Faso":                      "226",
	"Burundi":                           "257",
	"Cambodia":                          "855",
	"Cameroon":                          "237",
	"Canada":                            "1",
	"Cabo Verde":                        "238",
	"Cayman Islands":                    "1-345",
	"Central African Republic":          "236",
	"Chad":                              "235",
	"Chile":                             "56",
	"China":                             "86",
	"Christmas Island":                  "61",
	"Colombia":                          "57",
	"Comoros":                           "269",
	"Congo":                             "242",
	"Cook Islands":                      "682",
	"Costa Rica":                        "506",
	"Côte d'Ivoire":                     "225",
	"Croatia":                           "385",
	"Cuba":                              "53",
	"Curaçao":                           "599",
	"Cyprus":                            "357",
	"Czechia":                           "420",
	"Denmark":                           "45",
	"Djibouti":                          "253",
	"Dominica":                          "1-767",
	"Dominican Republic":                "1-809",
	"Ecuador":                           "593",
	"Egypt":                             "20",
	"El Salvador":                       "503",
	"Equatorial Guinea":                 "240",
	"Eritrea":                           "291",
	"Estonia":                           "372",
	"Eswatini":                          "748",
	"Ethiopia":                          "251",
	"Faroe Islands":                     "298",
	"Fiji":                              "679",
	"Finland":                           "358",
	"France":                            "33",
	"French Guiana":                     "594",
	"French Polynesia":                  "689",
	"French Southern Territories":       "262",
	"Gabon":                             "241",
	"Gambia":                            "220",
	"Georgia":                           "995",
	"Germany":                           "49",
	"Ghana":                             "233",
	"Gibraltar":                         "350",
	"Greece":                            "30",
	"Greenland":                         "299",
	"Grenada":                           "1-473",
	"Guadeloupe":                        "590",
	"Guam":                              "1-671",
	"Guatemala":                         "502",
	"Guernsey":                          "44-1481",
	"Guinea":                            "224",
	"Guinea-Bissau":                     "245",
	"Guyana":                            "592",
	"Haiti":                             "509",
	"Heard Island and McDonald Islands": "672",
	"Holy See":                          "379",
	"Honduras":                          "504",
	"Hong Kong":                         "852",
	"Hungary":                           "36",
	"Iceland":                           "354",
	"India":                             "91",
	"Indonesia":                         "62",
	"Iraq":                              "964",
	"Ireland":                           "353",
	"Isle of Man":                       "44-1624",
	"Israel":                            "972",
	"Italy":                             "39",
	"Jamaica":                           "1-876",
	"Japan":                             "81",
	"Jersey":                            "44-1534",
	"Jordan":                            "962",
	"Kazakhstan":                        "7",
	"Kenya":                             "254",
	"Kiribati":                          "686",
	"Korea":                             "Republic of",
	"Kuwait":                            "965",
	"Kyrgyzstan":                        "996",
	"Lao People's Democratic Republic":  "856",
	"Latvia":                            "371",
	"Lebanon":                           "961",
	"Lesotho":                           "266",
	"Liberia":                           "231",
	"Libya":                             "218",
	"Liechtenstein":                     "423",
	"Lithuania":                         "370",
	"Luxembourg":                        "352",
	"Macao":                             "853",
	"Macedonia":                         "the former Yugoslav Republic of",
	"Madagascar":                        "261",
	"Malawi":                            "265",
	"Malaysia":                          "60",
	"Maldives":                          "960",
	"Mali":                              "223",
	"Malta":                             "356",
	"Marshall Islands":                  "692",
	"Martinique":                        "596",
	"Mauritania":                        "222",
	"Mauritius":                         "230",
	"Mayotte":                           "262",
	"Mexico":                            "52",
	"Moldova":                           "Republic of",
	"Monaco":                            "377",
	"Mongolia":                          "976",
	"Montenegro":                        "382",
	"Montserrat":                        "1-664",
	"Morocco":                           "212",
	"Mozambique":                        "258",
	"Myanmar":                           "95",
	"Namibia":                           "264",
	"Nauru":                             "674",
	"Nepal":                             "977",
	"Netherlands":                       "31",
	"Netherlands Antilles":              "599",
	"New Caledonia":                     "687",
	"New Zealand":                       "64",
	"Nicaragua":                         "505",
	"Niger":                             "227",
	"Nigeria":                           "234",
	"Niue":                              "683",
	"Norfolk Island":                    "672",
	"North Macedonia":                   "807",
	"Northern Mariana Islands":          "1-670",
	"Norway":                            "47",
	"Oman":                              "968",
	"Pakistan":                          "92",
	"Palau":                             "680",
	"Palestine":                         "State of",
	"Panama":                            "507",
	"Papua New Guinea":                  "675",
	"Paraguay":                          "595",
	"Peru":                              "51",
	"Philippines":                       "63",
	"Pitcairn":                          "64",
	"Poland":                            "48",
	"Portugal":                          "351",
	"Puerto Rico":                       "1-787",
	"Qatar":                             "974",
	"Réunion":                           "262",
	"Romania":                           "40",
	"Russian Federation":                "7",
	"Rwanda":                            "250",
	"Saint Barthélemy":                  "590",
	"Saint Helena":                      "Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis":             "1-869",
	"Saint Lucia":                       "1-758",
	"Saint Pierre and Miquelon":         "508",
	"Saint Vincent and the Grenadines":  "1-784",
	"Samoa":                             "685",
	"San Marino":                        "378",
	"Sao Tome and Principe":             "239",
	"Saudi Arabia":                      "966",
	"Senegal":                           "221",
	"Serbia":                            "381",
	"Seychelles":                        "248",
	"Sierra Leone":                      "232",
	"Singapore":                         "65",
	"Slovakia":                          "421",
	"Slovenia":                          "386",
	"Solomon Islands":                   "677",
	"Somalia":                           "252",
	"South Africa":                      "27",
	"South Georgia and the South Sandwich Islands": "500",
	"South Sudan":              "211",
	"Spain":                    "34",
	"Sri Lanka":                "94",
	"Sudan":                    "249",
	"Suriname":                 "597",
	"Svalbard and Jan Mayen":   "47",
	"Swaziland":                "268",
	"Sweden":                   "46",
	"Switzerland":              "41",
	"Syrian Arab Republic":     "963",
	"Taiwan":                   "Province of China",
	"Tajikistan":               "992",
	"Tanzania":                 "United Republic of",
	"Thailand":                 "66",
	"Timor-Leste":              "670",
	"Togo":                     "228",
	"Tokelau":                  "690",
	"Tonga":                    "676",
	"Trinidad and Tobago":      "1-868",
	"Tunisia":                  "216",
	"Turkey":                   "90",
	"Turkmenistan":             "993",
	"Turks and Caicos Islands": "1-649",
	"Tuvalu":                   "688",
	"Uganda":                   "256",
	"Ukraine":                  "380",
	"United Arab Emirates":     "971",
	"United Kingdom of Great Britain and Northern Ireland": "44",
	"United States of America":                             "1",
	"United States Minor Outlying Islands":                 "1",
	"Uruguay":                                              "598",
	"Uzbekistan":                                           "998",
	"Vanuatu":                                              "678",
	"Vietnam":                                              "84",
	"Wallis and Futuna":                                    "681",
	"Western Sahara":                                       "212",
	"Yemen":                                                "967",
	"Zambia":                                               "260",
	"Zimbabwe":                                             "263",
}

func init() {
	for country, alpha2 := range countryCodeAlpha2MapByCountry {
		countryMapByAlpha2CountryCode[alpha2] = country
	}

	for alpha2, alpha3 := range countryCodeAlpha3MapAlpha2CountryCode {
		countryCodeAlpha2MapAlpha3CountryCode[alpha3] = alpha2
	}

	for country, alpha3 := range countryMapByAlpha3CountryCode {
		countryMapByAlpha3CountryCode[alpha3] = country
	}

	for numericCode, alpha3 := range countryCodeAlpha3MapByNumeric {
		numericCodeMapByAlpha3CountryCode[alpha3] = numericCode
	}

	for numericCode, alpha2 := range countryCodeAlpha2MapByNumericCode {
		numericCodeMapByCountryCodeAlpha2[alpha2] = numericCode
	}

	for country, numericCode := range numericCodeMapByCountry {
		countryMapByNumeric[numericCode] = country
	}
}

func GetAlpha2CodeByCountry() map[string]string {
	return countryCodeAlpha2MapByCountry
}

func GetCountryByAlpha2Code() map[string]string {
	return countryMapByAlpha2CountryCode
}

func GetAlpha3CodeByAlpha2Code() map[string]string {
	return countryCodeAlpha3MapAlpha2CountryCode
}

func GetAlpha2CodeByAlpha3Code() map[string]string {
	return countryCodeAlpha2MapAlpha3CountryCode
}

func GetAlpha3CodeByCountry() map[string]string {
	return countryMapByAlpha3CountryCode
}

func GetCountryByAlpha3Code() map[string]string {
	return countryMapByAlpha3CountryCode
}

func GetAlpha3CountryCodeByNumeric() map[string]string {
	return countryCodeAlpha3MapByNumeric
}

func GetNumericByAlpha3CountryCode() map[string]string {
	return numericCodeMapByAlpha3CountryCode
}

func GetAlpha2CountryCodeByNumeric() map[string]string {
	return countryCodeAlpha2MapByNumericCode
}

func GetNumericByAlpha2CountryCode() map[string]string {
	return numericCodeMapByCountryCodeAlpha2
}

func GetNumericCodeByCountry() map[string]string {
	return numericCodeMapByCountry
}

func GetCountryByNumericCode() map[string]string {
	return countryMapByNumeric
}

func GetPhoneCodeByCountry() map[string]string {
	return phoneCodeMapByCountry
}
